name: Crawler

on:
  schedule:
    - cron : '*/30 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          REST_DB_KEY: ${{ secrets.REST_DB_KEY }}
        run: ./gradlew run
