name: Crawler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run
        env:
          ENV_KEY_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          ENV_KEY_LATEST_VIEW_COMPANY_ID: ${{ secrets.LATEST_VIEW_COMPANY_ID }}
        run: ./gradlew run
