name: Crawler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          LATEST_VIEW_COMPANY_ID: ${{ secrets.LATEST_VIEW_COMPANY_ID }}
        run: ./gradlew run
      
      - name: Update Company Id
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'LATEST_VIEW_COMPANY_ID'
          value: ${{ env.LATEST_VIEW_COMPANY_ID }}
          repository: JSpiner/wanted-sauron
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
